import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FEVM NextJS Starter</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton showBalance />

        <h1 className={styles.title}>
          Welcome to Wallaby Testnet Starter +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://medium.com/@rvk_rishikesh/build-your-first-datadao-on-fvm-6ed38b940103" className={styles.card}>
            <h2>Build your first DataDAO on FVM&rarr;</h2>
            <p>Learn how to build your first DataDAO with this official documentation.</p>
          </a>

          <a href="https://docs.filecoin.io/fvm/basics/quickstart/" className={styles.card}>
            <h2>FVM Quickstart Guide &rarr;</h2>
            <p>Learn how to interact with FVM and build your DApps.</p>
          </a>

          <a
            href="https://docs.google.com/document/d/1KUcG2I0QfGAH80T4EqlV8p5jY1Li33wqFSiKc3yfP0A/edit?usp=sharing"
            className={styles.card}
          >
            <h2>Lending Pool&rarr;</h2>
            <p>A Detailed Cookbook on how to build a Lending Pool with Lotus and FEVM</p>
          </a>

          <a href="https://fvm.dev/" className={styles.card}>
            <h2>FEVM Official Site &rarr;</h2>
            <p>Official site for FVM for other references, etc..</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export default Home;
